# Khai báo các biến môi trường
image: docker/compose:1.29.2
services:
  - docker:dind
# Khai báo các biến môi trường
variables:
  IMAGE_NAME: trungchanhdev/gitlab-cicd-app
  TAG_NAME: demo-app
  DOCKER_HOST: tcp://docker:2375/
# Cac stage chinh
stages:
  - test
  - build
  - push
  - deploy
before_script:
  - echo "Mbappe2024_" | docker login -u "trungchanhdev" --password-stdin
# Hàm kiểm tra một service
.test_template:
  stage: test
  image: node:20-alpine
# Hàm build một service
.build_template:
  stage: build
  image: docker:stable
  services:
    - docker:dind

.deploy_template:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - echo "Mbappe2024_" | docker login -u "trungchanhdev" --password-stdin
# Khai báo các bước test cho từng service
test_passengersService:
  extends:
    - .test_template
  script:
    - cd passengersService
    - npm install
    - npm test
  only:
    - chanh
test_busesService:
  extends:
    - .test_template
  script:
    - cd busesService
    - npm install
    - npm test
  only:
    - chanh
test_driversService:
  extends:
    - .test_template
  script:
    - cd driversService
    - npm install
    - npm test
  only:
    - chanh
test_routesService:
  extends:
    - .test_template
  script:
    - cd routesService
    - npm install
    - npm test
  only:
    - chanh
test_ticketsService:
  extends:
    - .test_template
  script:
    - cd ticketsService
    - npm install
    - npm test
  only:
    - chanh
test_gateWayService:
  extends:
    - .test_template
  script:
    - cd gateWayService
    - npm install
    - npm test
  only:
    - chanh
buid_all_services:
  stage: build
  script:
    - docker-compose -f "docker-compose.yaml" up -d --build
push_all_services:
  stage: push
  script:
    - docker tag mongodb/mongodb-enterprise-server:latest trungchanhdev/gitlab-cicd-app:mongodb
    - docker push trungchanhdev/gitlab-cicd-app:mongodb
    - docker tag redis:latest trungchanhdev/gitlab-cicd-app:redis
    - docker push trungchanhdev/gitlab-cicd-app:redis
    - docker-compose -f "docker-compose.yaml" push
