variables:
  IMAGE_NAME: trungchanhdev/gitlab-cicd-app
  IMAGE_TAG: demo-cicd-app
  DOCKER_HOST: tcp://docker:2375/

stages:
  - test
  - build

# Hàm cài đặt các gói cho một service
.cache_install:
  before_script:
    - npm install

# Hàm kiểm tra một service
.test_template:
  stage: test
  image: node:20-alpine
  script:
    - npm test

# Hàm build một service
.build_template:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - echo "Mbappe2024_" | docker login -u "trungchanhdev" --password-stdin
# Khai báo các bước test cho từng service
test_busesService:
  extends:
    - .test_template
    - .cache_install
  script:
    - cd busesService
    - npm install
    - npm test

# Khai báo các bước build cho từng service
build_busesService:
  extends:
    - .build_template
  script:
    - cd busesService
    - docker build -t trungchanhdev/gitlab-cicd-app:latest .
    - docker push trungchanhdev/gitlab-cicd-app:latest
  only:
    - main
