# Khai báo các biến môi trường
variables:
  IMAGE_NAME: trungchanhdev/gitlab-cicd-app
  TAG_NAME: demo-app
  DOCKER_HOST: tcp://docker:2375/
# Cac stage chinh
stages:
  - test
  - build
  - deploy
# Hàm kiểm tra một service
.test_template:
  stage: test
  image: node:20-alpine
  script:
    - npm test
# Hàm build một service
.build_template:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - echo "Mbappe2024_" | docker login -u "trungchanhdev" --password-stdin
.deploy_template:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - echo "Mbappe2024_" | docker login -u "trungchanhdev" --password-stdin
# Khai báo các bước test cho từng service
test_passengersService:
  extends:
    - .test_template
  script:
    - cd passengersService
    - npm install
    - npm test
  only:
    - main
test_busesService:
  extends:
    - .test_template
  script:
    - cd busesService
    - npm install
    - npm test
  only:
    - main
test_driversService:
  extends:
    - .test_template
  script:
    - cd driversService
    - npm install
    - npm test
  only:
    - main
test_routesService:
  extends:
    - .test_template
  script:
    - cd routesService
    - npm install
    - npm test
  only:
    - main
test_ticketsService:
  extends:
    - .test_template
  script:
    - cd ticketsService
    - npm install
    - npm test
  only:
    - main
# Khai báo các bước build cho từng service
build_passengersService:
  extends:
    - .build_template
  script:
    - cd passengersService
    - docker build -t $IMAGE_NAME:passengersService .
    - docker push $IMAGE_NAME:passengersService
  only:
    - main
build_busesService:
  extends:
    - .build_template
  script:
    - cd busesService
    - docker build -t $IMAGE_NAME:busesService .
    - docker push $IMAGE_NAME:busesService
  only:
    - main
build_driversService:
  extends:
    - .build_template
  script:
    - cd driversService
    - docker build -t $IMAGE_NAME:driversService .
    - docker push $IMAGE_NAME:driversService
  only:
    - main
build_routesService:
  extends:
    - .build_template
  script:
    - cd routesService
    - docker build -t $IMAGE_NAME:routesService .
    - docker push $IMAGE_NAME:routesService
  only:
    - main
build_ticketsService:
  extends:
    - .build_template
  script:
    - cd ticketsService
    - docker build -t $IMAGE_NAME:ticketsService .
    - docker push $IMAGE_NAME:ticketsService
  only:
    - main
# Khai báo các bước deploy cho từng service
deploy_passengersService:
  extends:
    - .deploy_template
  script:
    - cd passengersService
    - docker pull $IMAGE_NAME:passengersService
    - docker run -d -p 80:80 $IMAGE_NAME:passengersService
  only:
    - main
