variables:
  DOCKER_DRIVER: overlay2
  IMGAGE_NAME: trungchanhdev/gitlab-cicd-app
  USER_NAME: trungchanhdev
  DOCKER_HOST: tcp://docker:2375
  PASSWORD: Mbappe2024_

image: docker/compose:1.29.2

services:
  - docker:dind

stages:
  - test
  - build
  - push
  - deploy

before_script:
  - echo $PASSWORD | docker login -u $USER_NAME --password-stdin

# Test the project
test-project:
  stage: test
  script:
    - echo "Testing the project..."
  only:
    - chanh

# Build Docker image
build-docker-image:
  stage: build
  script:
    - docker-compose -f "docker-compose.yaml" up -d --build
    - docker tag mongodb/mongodb-enterprise-server:latest trungchanhdev/gitlab-cicd-app:mongodb
    - docker tag redis:latest trungchanhdev/gitlab-cicd-app:redis
    - docker push trungchanhdev/gitlab-cicd-app:mongodb
    - docker push trungchanhdev/gitlab-cicd-app:redis
    - docker-compose -f "docker-compose.yaml" push
  only:
    - chanh

# Push to Docker Hub
push-docker-hub:
  stage: push
  script:
    - echo "Pushing the Docker image to Docker Hub..."
  only:
    - chanh

# Deploy to Docker Hub
deploy-ec2-instance:
  stage: deploy
  script:
    - echo "Deloy app to EC2 instance"
  only:
    - chanh
