variables:
  IMAGE_NAME: trungchanhdev/gitlab-cicd-app
  IMAGE_TAG: demo-cicd-app

stages:
  - test
  - build

# Hàm cài đặt các gói cho một service
.cache_install:
  before_script:
    - npm install

# Hàm kiểm tra một service
.test_template:
  stage: test
  image: node:20-alpine
  script:
    - npm test

# Hàm build một service
.build_template:
  stage: build
  image: docker:20.18.16
  services:
    - docker:docker:20.18.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  script:
    - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
    - docker push "$IMAGE_NAME:$IMAGE_TAG"

# Khai báo các bước test cho từng service
test_busesService:
  extends:
    - .test_template
    - .cache_install
  script:
    - cd busesService
    - npm install
    - npm test

# Khai báo các bước build cho từng service
build_busesService:
  extends:
    - .build_template
    - .cache_install
  script:
    - cd busesService
    - npm install
    - npm run build
  only:
    - main
